Add expanding manual filename globs in database
When user manually enters a file path w/ globs...
   ~/bin/*.sh
...it is now correctly expanded as if entered on the CLI.

diff --git a/conf b/conf
--- a/conf
+++ b/conf
@@ -1,5 +1,5 @@
 #!/bin/bash
-# vim: ft=bash tw=80
+# vim: ft=bash tw=80 foldmethod=marker foldclose=all
 #
 # shellcheck disable=SC2016,SC2128,SC2178,SC2206
 # ^-- really doesn't understand namerefs, also I promise I know when I'm puting
@@ -161,10 +161,14 @@ function db_load {
       if ! local -n entry_r="$ENTRY" 2>/dev/null ; then
          printf '(Unexpected indent on line %d.)\n'  "$lineno" >&2
          exit 1
+      else
+         local -n items_r="${entry_r['items']}"
       fi
 
-      local -n items_r="${entry_r['items']}"
-      items_r=( ${line##* } )
+      # Expands literal db entries containing filename globs.
+      mapfile -t items_r < <(
+         xargs -I{} bash -c "printf '%s\n' {}" <<< "${line##* }"
+      )
    done < "$DATA_FILE"
 
    db_validate
@@ -191,7 +195,10 @@ function db_validate {
       local path
       for path in "${items_r[@]}" ; do
          if [[ ! -f $path ]] || [[ ! -r $path ]] ; then
-            printf 'Does not exist, or cannot read: %s\n'  "$path"
+            { printf '(Does not exist, or cannot read literal:\n'
+              printf "  '%s'\n"  "$path"
+              printf ')\n'
+            } >&2
             exit 1
          fi
       done
@@ -209,7 +216,7 @@ function cmd_single_arg {
 }
 
 #                                command :: dir
-#-------------------------------------------------------------------------------
+#----------------------------------------------------------------------------{{{
 function usage_dir {
    local outfile
    case "$1" in
@@ -276,9 +283,10 @@ function cmd_dir {
       . ~/.bashrc ; export PS1="[conf] ${PS1}"
    ')
 }
+#}}}
 
 #                                command :: set
-#-------------------------------------------------------------------------------
+#----------------------------------------------------------------------------{{{
 function usage_set {
 cat <<EOF
 usage: conf set NICK path1 [ ,pathN]
@@ -356,9 +364,10 @@ function cmd_set {
    db_validate
    db_store
 }
+#}}}
 
 #                                command :: edit
-#-------------------------------------------------------------------------------
+#----------------------------------------------------------------------------{{{
 function usage_edit {
    local outfile
    case "$1" in
@@ -426,9 +435,10 @@ function cmd_edit {
    cd "${items_r[0]%/*}"
    exec $EDITOR  "${ARGS[@]}"  "${items_r[@]}"
 }
+#}}}
 
 #                               command :: sort
-#-------------------------------------------------------------------------------
+#----------------------------------------------------------------------------{{{
 function usage_sort {
    local outfile
    case "$1" in
@@ -476,9 +486,10 @@ function cmd_sort {
    )
    db_store
 }
+#}}}
 
 #                               command :: clean
-#-------------------------------------------------------------------------------
+#----------------------------------------------------------------------------{{{
 function usage_clean {
    local outfile
    case "$1" in
@@ -546,9 +557,10 @@ function cmd_clean {
    | head --lines=-5      \
    | xargs rm "${rm[@]}"
 }
+#}}}
 
 #                                command :: db
-#-------------------------------------------------------------------------------
+#----------------------------------------------------------------------------{{{
 function usage_db {
    local outfile
    case "$1" in
@@ -597,9 +609,10 @@ function cmd_db {
    parse_args_db "$@"
    exec $EDITOR  "${ARGS[@]}"  "${DATA_FILE}"
 }
+#}}}
 
 #                               command :: help
-#-------------------------------------------------------------------------------
+#----------------------------------------------------------------------------{{{
 function cmd_help {
    # Ignore flags and `conf help help`. Convert to dict for easier lookup.
    local -A valid=()
@@ -621,6 +634,7 @@ function cmd_help {
 
    usage_"$1" 0
 }
+#}}}
 
 #                                    engage
 #-------------------------------------------------------------------------------
